### ISSUE TITLE
Have `autorenew` command throw a non-zero exit 

### ISSUE THREAD

**Issue by bitsapien** [sorah/acmesmith#18]
I have a cron to renew my certificates that runs everyday. I'm utilising the `autorenew` command to do this in the script below. There needs to be a way to figure out that renewal was not required so I can skip fetching and writing the certificates to disk all the time.

```shell
#!/bin/bash

/usr/local/bin/acmesmith autorenew -d10 -c /tmp/acmesmith.yml

/usr/local/bin/acmesmith save-certificate lmu.abc.com --output=/etc/nginx/ssl/lmu.abc.com/fullchain.pem  -c /tmp/acmesmith.yml
/usr/local/bin/acmesmith save-private-key lmu.abc.com --output=/etc/nginx/ssl/lmu.abc.com/privkey.pem -c /tmp/acmesmith.yml
```

One solution is to have the `autorenew` command throw a non-zero exit if the certificates do not need renewal.

**Comment by sorah** [comment]
how about using post issuing hooks?

**Comment by bitsapien** [comment]
Thanks, that helped solve my case.
