### ISSUE TITLE
Lazy authorize command, or command to verify authorizations

### ISSUE THREAD

**Issue by dtaylor-iidnet** [sorah/acmesmith#23]
Hi Folks,

Great tool.
I'm automating with ansible, and would like to be able to run the authorize tool without it doing the slow (well it's slow if I'm doing more than 3 SANs, and Letsencrypt supports up to 100) DNS stuff for every SAN in a cert.
Could you either expose the verify step so that I can check if my SANs are authorized, so I can skip the authorize step, or could you just verify the SANs in a request first (as well as last), and skip the already authorized ones.
Also, what's the best way for me to know if my registration is good already, as this fails if I try to run it twice.
One fix for all this is to delete the entire bucket subdir under which all this sits, but I guess it's not your intention, as you would not have built in versioning support otherwise.

Thanks in advance.
Regards, David

**Comment by sorah** [comment]
The latest release run acquiring authorizations before requesting certs if a domain hasn't been authorized yet.  This behavior doesn't satisfy your use case?

**Comment by sorah** [comment]
Since v0.6.0 https://github.com/sorah/acmesmith/releases/tag/v0.6.0

**Comment by sorah** [comment]
Closing due to no response for a while.
