### ISSUE TITLE
The autorenew command to read the config file

### ISSUE THREAD

**Issue by jhundley9109** [sorah/acmesmith#25]
Hello!

I love this project, it has saved much time and effort in managing our SSL certs!

Anyways, I noticed that the way the autorenew command when using the S3 storage options works is either you optionally pass in a CN to the command or if you don't, it defaults to attempt to autorenew all the domains associated to your account that are listed in your bucket. I use multiple servers with different domains on them but they all use the same account. I think the autorenew command could read for the s3 bucket by checking the acmesmith.yml config file for the appropriate domains to search through instead of trying to autorenew them all.

For now my workaround is to just run the command for each domain to attempt to autorenew them individually but it would be nice to just run the autorenew command with the supplied config file and it attempts to autorenew the CNs listed there.

Let me know what you think!

**Comment by sorah** [comment]
Sounds good, pull request welcomed.

**Comment by jhundley9109** [comment]
Okay, cool. I'll take a look at it. 

I only have learned this project well enough to know how to implement what I needed to get the certs created, but not well enough to make changes yet. If I come up with something, I'll check back here with the PR.

**Comment by jhundley9109** [comment]
After digging through the code I realized two things.
1. I was using acmesmith-http-path extension and thinking I could use that the domains listed under the http_path key as the basis for the default value of the auto-renew. So that is kinda outside the scope of this project I think.
2. I can get the basic functionality I was looking for, which is running multiple auto-renews on different domains in one command, by just doing a space delimited string for the second parameter to the auto-renew function. As ruby isn't my first language, I didn't realize that is what the * operator was doing.

Thanks anyways!
