### ISSUE TITLE
Request changing rrset for Cross-Account(AWS Route53)

### ISSUE THREAD

**Issue by kuritan** [sorah/acmesmith#38]
Hi,
I got a use case that I had a administrator AWS account and servals developer account.
For security purpose, I can't allow developers access the administrator account.
And, I also had a Hosted Zone in administrator account(Main domain), sub domains were hosted on per develop account.

When I use acmesmith to request changing RRset, I got an error.
like:
`{"type"=>"urn:ietf:params:acme:error:dns", "detail"=>"DNS problem: NXDOMAIN looking up TXT for _acme-challenge.develop.example.com - check that a DNS record exists for this domain", "status"=>400}`

Anyway, I figure out what happened.
The SOA record hosted on developer account's Hosted Zone(develop.example.com).
But, I used administrator account's credential to access AWS.
So, acmesmith can't upset a RRset for developer account's Hosted Zone(develop.example.com).
P.S. I got servals developer account, but a unified ssl certificate request platform(base on acmesmith lib) 

So, I modify some code and created a pr.
It worked pretty good in my case.

Thank you very much with your acmesmith.

**Comment by sorah** [comment]
Hi, I cannot correctly understand your request (and this issue sounds different with #39)...

I have just released [v2.3.0](vhttps://github.com/sorah/acmesmith/releases/tag/v2.3.0) which allows use of `sts:AssumeRole` when updating Route 53 hosted zones.

If you have `develop.example.com` zone in your development account & NS delegation & IAM role are correctly set up, you can use `assume_role:` to update the zone from the administrator account.

```yaml
challenge_responders:
  - route53:
      assume_role:
        role_arn: arn:aws:iam:::...
    filter:
      subject_name_suffix: [develop,example.com]
```
