### ISSUE TITLE
Incompatible with acme-client 0.3.2-0.3.6

### ISSUE THREAD

**Issue by wjordan** [sorah/acmesmith#8]
A breaking change in unixcharles/acme-client#66 (published to RubyGems in v`0.3.2`) caused `acmesmith` to fail with `uninitialized constant Acme (NameError)` because this library uses `require 'acme/client'`. This change was reverted in unixcharles/acme-client#83 (not yet published to RubyGems), so future versions should work again. However, this means that all versions of `acmesmith` are broken when used with `acme-client` 0.3.2 through 0.3.6.

Possible fixes for future release of `acmesmith`:

- Change `require acme/client` to `require acme-client`
- Pin `acme-client` dependency to `['< 0.3.2'], ['> 0.3.6']` to avoid the incompatible versions

**Comment by sorah** [comment]
thank you for letting me know, I'll check then fix later

**Comment by sorah** [comment]
Released v0.4.1 which now use `acme-client` to require.
